BetterTwitter/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from MyTwitter import views

urlpatterns = [
    url('^admin/', admin.site.urls),
    url(r'^mytwitter/', include('MyTwitter.urls')),
    url(r'^api/mytwitter/', include('MyTwitter.api.urls', namespace='api-mytwitter')),

]

MyTwitter/api/urls.py
from django.conf.urls import url


from . import views
urlpatterns = [
    url(r'^(?P<pk>(\d)+)/$', views.TweetRudView.as_view(), name='tweet-rud'),
    url(r'^create/$', views.TweetCreateView.as_view(), name='tweet-create'),

]

MyTwitter/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.TweetViewAll.as_view(), name='all-tweets'),
    url(r'^likes/(?P<tweet_id>(\d)+)/$', views.TweetLikeToggle.as_view(), name='likes'),
    url(r'^api/likes/(?P<tweet_id>(\d)+)/$', views.TweetLikeAPIToggle.as_view(), name='likes-api'),
    url(r'^create-tweet/$', views.CreateTweetView.as_view(), name='create-tweet'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^add-user/$', views.CreateUserView.as_view(), name='create-user'),
    url(r'^user-tweets/(?P<user_id>(\d)+)/$', views.UserTweetsView.as_view(), name='user-tweets'),
    url(r'^comments/(?P<tweet_id>(\d)+)/$', views.CommentsView.as_view(), name='comments'),
    url(r'^correspondence/(?P<user_id>(\d)+)/$', views.CorrespondenceView.as_view(), name='correspondence'),
    url(r'^user-site/$', views.UserSiteView.as_view(), name='user-site'),
    url(r'^update-user/$', views.UserUpdateView.as_view(), name='update-user'),
    url(r'^message/(?P<msg_id>(\d)+)/$', views.MessageView.as_view(), name='message')

]

MyTwitter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class Tweet(models.Model):

    content = models.CharField(max_length=140)
    creation_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, blank=True, related_name='post_likes')

    class Meta:
        ordering = ['-creation_date']

    def get_absolute_url(self):
        return reverse('user-tweets', kwargs={'user_id': self.user.id})

    def get_like_url(self):
        return reverse('likes', kwargs={'tweet_id': self.id})

    def get_like_api_url(self):
        return reverse('likes-api', kwargs={'tweet_id': self.id})

    def __str__(self):
        return self.content


class Comment(models.Model):

    comment = models.CharField(max_length=60)
    creation_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment


class Message(models.Model):

    subject = models.CharField(max_length=150)
    content = models.TextField()
    to = models.ForeignKey(User, related_name='receiver', on_delete=models.CASCADE)
    who_sent = models.ForeignKey(User, related_name='sender', on_delete=models.CASCADE)
    date_sent = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    time_read = models.DateTimeField(null=True)

    def __str__(self):
        return self.subject

MyTwitter/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import ModelForm, Textarea
from django.contrib.auth import authenticate, get_user_model
from .models import Tweet, Comment, Message

User = get_user_model()


class TweetForm(ModelForm):

    class Meta:
        model = Tweet
        fields = ['content']

        widgets = {
                'content': Textarea(attrs={'cols': 30, 'rows': 5}),
        }


class UserForm(forms.Form):
    login = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = None

    def clean(self):
        cleaned_data = super().clean()

        user = authenticate(
            username=cleaned_data['login'],
            password=cleaned_data['password']
        )

        if user is None:
            raise forms.ValidationError('Invalid credentials')

        self.user = user
        return cleaned_data


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ['comment']


class MessageForm(ModelForm):

    class Meta:
        model = Message
        fields = ['subject', 'content']

        widgets = {
            'content': Textarea(attrs={'cols': 30, 'rows': 5}),
        }


class CorrespondenceForm(forms.Form):
    username = forms.ModelChoiceField(label='friends', queryset=User.objects.all())

    def __init__(self, current_user, *args, **kwargs):
        super(CorrespondenceForm, self).__init__(*args, **kwargs)
        self.fields['username'].queryset = self.fields['username'].queryset.exclude(id=current_user.id)

MyTwitter/api/views.py
from rest_framework import generics, mixins
from MyTwitter.models import Tweet
from .serializers import TweetSerializer


class TweetCreateView(mixins.CreateModelMixin, generics.ListAPIView): #CreatelView
    lookup_field = 'pk'
    serializer_class = TweetSerializer
    # queryset = Tweet.objects.all()

    def get_queryset(self):
        qs = Tweet.objects.all()
        query = self.request.GET.get('q')
        if query is not None:
            qs = qs.filter(content__icontains=query)
        return qs

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)



class TweetRudView(generics.RetrieveUpdateDestroyAPIView): #DetailView
    lookup_field = 'pk'
    serializer_class = TweetSerializer
    # queryset = Tweet.objects.all()

    def get_queryset(self):
        return Tweet.objects.all()

    # def get_object(self):
    #     pk = self.kwargs.get('pk')
    #     return Tweet.objects.get(pk=pk)

MyTwitter/views.py
from django.db.models import Q
from django.views import View
from .models import Tweet, Comment, Message
from .forms import (TweetForm,
                    UserForm,
                    SignUpForm,
                    CommentForm,
                    MessageForm,
                    CorrespondenceForm
                    )
from django.views.generic import (CreateView,
                                  ListView,
                                  UpdateView,
                                  DetailView,
                                  RedirectView
                                  )
from django.contrib.auth import (get_user_model,
                                 login,
                                 logout,
                                 authenticate
                                 )
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
User = get_user_model()


class TweetViewAll(LoginRequiredMixin, ListView):
    model = Tweet
    context_object_name = 'tweets'
    login_url = '/mytwitter/login'


class TweetLikeToggle(RedirectView):

    def get(self, *args, **kwargs):
        tweet_id = self.kwargs.get("tweet_id")
        print(tweet_id)
        tweet = get_object_or_404(Tweet, id=tweet_id)
        user = self.request.user
        if user.is_authenticated():
            if user in tweet.likes.all():
                tweet.likes.remove(user)
            else:
                tweet.likes.add(user)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER', '/'))


from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.contrib.auth.models import User


class TweetLikeAPIToggle(APIView):

    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, tweet_id=None, format=None):
        # tweet_id = self.kwargs.get("tweet_id")
        print(tweet_id)
        tweet = get_object_or_404(Tweet, id=tweet_id)
        user = self.request.user
        updated = False
        liked = False
        if user.is_authenticated():
            if user in tweet.likes.all():
                liked = False
                tweet.likes.remove(user)
            else:
                liked = True
                tweet.likes.add(user)
            updated = True
        data = {
            'updated': updated,
            'liked': liked
        }
        return Response(data)


class CreateTweetView(CreateView):
    form_class = TweetForm
    template_name = 'MyTwitter/tweet_form.html'
    success_url = '/mytwitter'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class LoginView(View):
    form_class = UserForm
    template_name = 'MyTwitter/user_form.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            login(request, form.user)
            return redirect('/mytwitter')
        else:
            return render(request, self.template_name, {'form': form})


class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('/mytwitter/login')


class CreateUserView(CreateView):
    form_class = SignUpForm
    success_url = '/mytwitter'
    template_name = 'MyTwitter/create_user_form.html'

    def form_valid(self, form):

        valid = super(CreateUserView, self).form_valid(form)
        username, password = \
            form.cleaned_data.get('username'), \
            form.cleaned_data.get('password1')
        new_user = authenticate(username=username, password=password)
        login(self.request, new_user)
        return valid


class UserTweetsView(View):
    template_name = 'MyTwitter/user_tweet_list.html'

    def get(self, request, user_id):
        user = get_object_or_404(User, id=user_id )
        return render(request, self.template_name, {'user': user})


class CommentsView(View):
    form_class = CommentForm
    template_name = 'MyTwitter/comment_form.html'

    def get(self, request, tweet_id):
        comments = Comment.objects.filter(tweet=tweet_id)
        tweet = get_object_or_404(Tweet, id=tweet_id)
        return render(request,
                      self.template_name,
                      {
                       'form': self.form_class(),
                       'comments': comments,
                       'tweet': tweet
                        })

    def post(self, request, tweet_id):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = self.request.user
            tweet = get_object_or_404(Tweet, id=tweet_id)
            comment = form.cleaned_data['comment']
            Comment.objects.create(comment=comment, user=user, tweet=tweet)
            return redirect('comments', tweet_id=tweet_id)
        return redirect('comments', tweet_id=tweet_id)


class UserSiteView(View):
    form_class = CorrespondenceForm
    template_name = 'MyTwitter/user_site.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class(self.request.user)})

    def post(self, request):
        form = self.form_class(self.request.user, data=request.POST)
        if form.is_valid():
            user = form.cleaned_data['username']
            return redirect('correspondence', user_id=user.id)
        return render(request, self.template_name, {'form': form})


class UserUpdateView(UpdateView):
    form_class = SignUpForm
    template_name = 'MyTwitter/update_user_form.html'
    success_url = '/mytwitter/login'

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj


class CorrespondenceView(View):
    form_class = MessageForm
    template_name = 'MyTwitter/message_form.html'

    def get(self, request, user_id):
        sender = self.request.user
        receiver = User.objects.get(id=user_id)
        messages = Message.objects.filter(Q(who_sent=sender, to=receiver) | Q(who_sent=receiver, to=sender))
        return render(request, self.template_name, {'form': self.form_class(),
                                                    'receiver': receiver,
                                                    'messages': messages,
                                                    })

    def post(self, request, user_id):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            sender = self.request.user
            receiver = User.objects.get(id=user_id)
            Message.objects.create(subject=form.cleaned_data['subject'],
                                   content=form.cleaned_data['content'],
                                   who_sent=sender,
                                   to=receiver)
            return redirect('correspondence', user_id=receiver.id)
        return render(request, self.template_name, {'form': form})


class MessageView(DetailView):
    model = Message
    pk_url_kwarg = 'msg_id'

MyTwitter/templates/MyTwitter/AllTweets.html
{% extends 'MyTwitter/base.html' %}

<head>
{% block head_title %}{{ block.super }}{% endblock head_title %}
</head>

<body>
{% block content %}

<h1>Tweets</h1>


<table>
    <tr>
        <th>User</th>
        <th>Tweet</th>
    </tr>
     {% for tweet in tweets %}
    <tr>
            <td>{{ user.username }}</td>
            <td>{{ tweet.content }}</td>
    </tr>
    {% endfor %}
</table>

<body>

{% endblock content%}

MyTwitter/templates/MyTwitter/Tweet_form.html
{% extends 'MyTwitter/base.html' %}

{% block title %}
    {{ block.super }}
{% endblock %}


{% block content %}

<form action="" method="post"> {% csrf_token %}
{{ form }}
<input type="submit" value="Dodaj">
</form>


{% endblock %}

MyTwitter/templates/MyTwitter/Tweet_list.html
{% extends 'MyTwitter/base.html' %}

<head>
{% block head_title %}{{ block.super }}{% endblock head_title %}
</head>

<body>
{% block content %}
<a id="rightcorner" href="{% url 'logout' %}">Logout</a>
<h1>Tweets</h1>
<h3><a href="{%  url 'user-site' %}">{{ user.username }}</a> logged in to the account</h3>
<a class='button-link' href="{% url 'create-tweet' %}">Add Tweet</a><br>

<table>
    <tr>
        <th>User</th>
        <th>Tweet</th>
        <th>Date</th>
        <th>Likes</th>
        <th>Comments</th>
    </tr>
     {% for tweet in tweets %}
    <tr>
        <td><a href="{{ tweet.get_absolute_url }}">{{ tweet.user.username }}</a></td>
        <td>{{ tweet.content }}</td>
        <td>{{ tweet.creation_date }}</td>
        <td><a class="btn btn-primary" data-href='{{ tweet.get_like_api_url }}' data-likes="{{ tweet.likes.count }}" href='{{ tweet.get_like_url }}'>{{ tweet.likes.count }} Likes</a></td>
        <td>{{ tweet.comment_set.all.count }}</td>
        <td><a href="{% url 'comments' tweet_id=tweet.id %}">Comments</a></td>
    </tr>
    {% endfor %}
</table>



</body>
{% endblock content%}

MyTwitter/templates/MyTwitter/base.html
{% load staticfiles %}

<!DOCTYPE html>

<html lang="en">

<head>

    <title>
        {% block head_title %}BetterTwitter.com{% endblock head_title %}
    </title>

    {% include 'snippets/css.html' %}
    <link rel="stylesheet" type="text/css" href="{% static 'MyTwitter/style.css' %}" />
</head>
<body>


<h1 style="color: black">Tweet yourself</h1>
<div class="alert alert-primary" role="alert">
       {% block content %}{% endblock %}
</div>


{% include 'snippets/js.html' %}

  <script>
     $(document).ready(function(){
          function updateText(btn, newCount, verb){
          btn.attr('data-likes', newCount)
          btn.text(newCount + " " + verb)
      }
      $(".btn").click(function(e){
        e.preventDefault()
        var this_ = $(this)
        var likeUrl = this_.attr("data-href")
        var likeCount = parseInt(this_.attr("data-likes")) | 0
        var addLike = likeCount + 1
        var removeLike = likeCount - 1
        if (likeUrl){
           $.ajax({
            url: likeUrl,
            method: "GET",
            data: {},
            success: function(data){
              console.log(data)
              var newLikes;
              if (data.liked){
                  updateText(this_, addLike, "Unlike")
              } else {
                  updateText(this_, removeLike, "Like")
              }
            }, error: function(error){
              console.log(error)
              console.log("error")
            }
          })
        }

      })
  })
</script>


<script>
    $(document).ready(function(){
        function updateRead(link, verb) {
            link.attr('data-read', verb)
            link.text(verb)
        }
     $('#read').click(function (e) {
         e.preventDefault()
         var msg_url = this.attr('href')
         var read = this.attr('data-read')
         if(msg_url){
             $.ajax({
                 url: msg_url,
                 method: 'GET',
                 data: {},
                 sucess: function(data){
                     console.log(data)
                     if (data.is_read === false){
                         updateRead(this, 'Read')
                         read = true
                     }

                 }
             })
         }
     })

    })


</script>

<script>
    $(document).ready(function(){
        {% block jquery %}{% endblock %}
    })
</script>

</body>
</html>

MyTwitter/templates/MyTwitter/comment_form.html
{% extends 'MyTwitter/base.html' %}

{% block title %}
    {{ block.super }}
{% endblock %}


{% block content %}

<a id="rightcorner" href="{% url 'logout' %}">Logout</a>
<h3>{{ request.user.username }} logged in to the account</h3>
<a href="{% url 'all-tweets' %}">Wall</a><br>
<h2>Tweet posted by: {{ tweet.user.username }}</h2>
<strong>{{ tweet.content }}</strong><br>


    {% for comment in comments %}
        <li>{{ comment.comment }}, {{ comment.user.username }},
            {{ comment.creation_date }}</li>
        {% empty %}
        No Comments
    {% endfor %}


<form action="" method="post"> {% csrf_token %}
{{ form }}
<input type="submit" value="Add Comment">
</form>


<a class='button-link' href="{% url 'user-tweets' user_id=tweet.user.id %}">Back</a>


{% endblock %}

MyTwitter/templates/MyTwitter/create_user_form.html
{% extends 'MyTwitter/base.html' %}

{% block title %}
    User|{{ block.super }}
{% endblock %}


{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Create">
</form>




{% endblock %}

MyTwitter/templates/MyTwitter/message_detail.html
{% extends 'MyTwitter/base.html' %}

{% block title %}
    {{ block.super }}
{% endblock %}


{% block content %}
<h3>Message from {{ object.who_sent.username }} to {{ object.to.username }}</h3>

<table>
<tr>
    <th>subject</th>
    <th>content</th>
</tr>
<tr>
    <td>{{ object.subject }}</td>
    <td>{{ object.content }}</td>
</tr>
</table>

{% if object.who_sent == request.user %}
    <a class='button-link' href="{% url 'correspondence' user_id=object.to.id %}">Back</a>
{% else %}
    <a class='button-link' href="{% url 'correspondence' user_id=object.who_sent.id %}">Back</a>
{% endif %}

{% endblock %}

MyTwitter/templates/MyTwitter/message_form.html
{% extends 'MyTwitter/base.html' %}

{% block title %}
    {{ block.super }}
{% endblock %}


{% block content %}
<h3>Correspondence with {{ receiver.username }}</h3>

<table>
        <tr>
            <th>from </th>
            <th>subject</th>
            <th>content</th>
            <th>sent</th>
            <th>read</th>
        </tr>
        {% for msg in messages %}
        <tr>
            {% if msg.who_sent == request.user %}
            <td>You</td>
            {% else %}
            <td>{{ msg.who_sent.username }}</td>
            {% endif %}
            <td><a id=read data-read='{{ msg.is_read }}' href="{% url 'message' msg_id=msg.id %}">{{ msg.subject }}</a></td>
            <td>{{ msg.content|truncatechars:10 }}</td>
            <td>{{ msg.date_sent }}</td>
            <td>{{ msg.time_read }}</td>
        </tr>
         {% endfor %}
</table>

<form action="" method="post"> {% csrf_token %}
{{ form }}
<input type="submit" value="Send">
</form>

<a class='button-link' href="{% url 'user-site' %}">Back</a>

{% endblock %}

MyTwitter/templates/MyTwitter/tweet_form.html
{% extends 'MyTwitter/base.html' %}

{% block title %}
    {{ block.super }}
{% endblock %}


{% block content %}

<form action="" method="post"> {% csrf_token %}
{{ form }}
<input type="submit" value="Tweet">
</form>

<a class='button-link' href="{% url 'user-site' %}">Back</a>


{% endblock %}

MyTwitter/templates/MyTwitter/update_user_form.html
{% extends 'MyTwitter/base.html' %}

{% block title %}
    User|{{ block.super }}
{% endblock %}


{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit" value="Update">
</form><br>

<a class='button-link' href="{% url 'user-site' %}">Back</a>



{% endblock %}

MyTwitter/templates/MyTwitter/user_form.html
{% extends 'MyTwitter/base.html' %}

{% block title %}
    User|{{ block.super }}
{% endblock %}


{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form }}
<input type="submit" value="Zaloguj">
</form>




{% endblock %}

MyTwitter/templates/MyTwitter/user_site.html
{% extends 'MyTwitter/base.html' %}

<head>
{% block head_title %}{{ block.super }}{% endblock head_title %}
</head>

<body>
{% block content %}

<a id="rightcorner" href="{% url 'logout' %}">Logout</a>
<h2>Your profile: {{ user.username }}</h2>
<a class='button-link' href="{% url 'create-tweet' %}">Add Tweet</a>
<a class='button-link' href="{% url 'all-tweets' %}">Wall</a>
<a class='button-link' href="{% url 'update-user' %}">Update your details</a>

<form class='button-link' method="post" action="">
    {% csrf_token %}
       {{ form }}
<input type="submit" value="Correspondence">
</form>


<table>
    <tr>
        <th>Tweet</th>
        <th>Date</th>
        <th>Likes</th>
        <th>Comments</th>
    </tr>
     {% for tweet in user.tweet_set.all %}
    <tr>
        <td>{{ tweet.content }}</td>
        <td>{{ tweet.creation_date }}</td>
        <td><a class="btn btn-primary" data-href='{{ tweet.get_like_api_url }}' data-likes="{{ tweet.likes.count }}" href='{{ tweet.get_like_url }}'>{{ tweet.likes.count }} Likes</a></td>
        <td><a href="{% url 'comments' tweet_id=tweet.id %}">Comments</a></td>
    </tr>
    {% endfor %}
</table>



{% endblock content %}

MyTwitter/templates/MyTwitter/user_tweet_list.html
{% extends 'MyTwitter/base.html' %}

<head>
{% block head_title %}{{ block.super }}{% endblock head_title %}
</head>

<body>
{% block content %}
<a id="rightcorner" href="{% url 'logout' %}">Logout</a>
<h3><a href="{%  url 'user-site' %}">{{ request.user.username }}</a> logged in to the account</h3>
<h2>Tweets posted by: {{ user.username }}</h2>
<a class='button-link' href="{% url 'create-tweet' %}">Add Tweet</a>
<a class='button-link' href="{% url 'all-tweets' %}">Wall</a>
    {% if request.user.id != user.id %}
<a class='button-link' href="{% url 'correspondence' user_id=user.id %}">Send {{ user.username }} a message</a>
    {% endif %}

<table>
    <tr>
        <th>Tweet</th>
        <th>Date</th>
        <th>Likes</th>
        <th>Comments</th>
    </tr>
     {% for tweet in user.tweet_set.all %}
    <tr>
        <td>{{ tweet.content }}</td>
        <td>{{ tweet.creation_date }}</td>
        <td><a class="btn btn-primary" data-href='{{ tweet.get_like_api_url }}' data-likes="{{ tweet.likes.count }}" href='{{ tweet.get_like_url }}'>{{ tweet.likes.count }} Likes</a></td>
        <td>{{ tweet.comment_set.all.count }}</td>
        <td><a href="{% url 'comments' tweet_id=tweet.id %}">Comments</a></td>
    </tr>
    {% endfor %}
</table>
</body>


{% endblock content%}